#!/bin/bash
pdflatex -shell-escape report.tex && \
pdflatex -shell-escape report.tex && \
pdflatex -shell-escape report.tex && \ 
bibtex report && \
pdflatex -shell-escape report.tex && \
pdflatex -shell-escape report.tex
open report.pdf

